### ISSUE TITLE
Получить ссылку на kodik плеер по shikimori_id

### ISSUE THREAD

**Issue by Levitskyy** [YaNesyTortiK/AnimeParsers#1]
Есть ли возможность получить ссылку на плеер кодик как в link из словаря base_search по shikimori_id, а не по названию?

**Comment by YaNesyTortiK** [comment]
Если я правильно понял, то добавил функции `base_search_by_id` и `search_by_id` в KodikParser (и в асинхронный соответственно). Обновись до версии 1.7.1
