### ISSUE TITLE
AniBoom парсер выдаёт embed ссылку на kodik

### ISSUE THREAD

**Issue by sandlotie** [YaNesyTortiK/AnimeParsers#4]
```py
animego_id = '1665'
await aniboom._get_embed_link(animego_id)
```
Возвращает ссылку: `https://kodik.info/seria/763279/.../720p`

`anime_parsers_ru==1.9.3`

**Comment by YaNesyTortiK** [comment]
Привет, не совсем понимаю как такое могло получится. 
Насколько я знаю animego.org (откуда брался aniboom плеер) некоторое время уже заблокирован.

Я, при включенном впн, запустил тесты и все что я получаю, что сервер возвращает ошибку 500. Самостоятельно если перейти по адресу, также возвращается ошибка 500. То есть сайт не работает.

Запустил код
```
parser = AniboomParser()
print(parser._get_embed_link('1665'))
```

И он мне соответственно также выдал ошибку 500.

Можешь поподробнее рассказать как это произошло?

**Comment by sandlotie** [comment]
Некоторые EU впны работают (Польша, Украина, прибалтика)

https://github.com/YaNesyTortiK/AnimeParsers/blob/e1dc1cd4b23bd838d08c033b3f92dff42eca0884/src/anime_parsers_ru/parser_aniboom.py#L360
Эта строка предполагает что первым будет AniBoom, что обычно так и есть, но конкретно у этого аниме первые две озвучки в плеере кодика и уже третяя это AniBoom
https://animego.org/anime/re-zhizn-v-alternativnom-mire-s-nulya-2-chast-2-1665

**Comment by YaNesyTortiK** [comment]
Спасибо за инфу, попробую посмотреть что с этим сделать. Как только пофикшу - напишу сюда и закрою.

**Comment by YaNesyTortiK** [comment]
@sandlotie 
Я вроде бы исправил ошибку, добавив дополнительное условие. Но у меня не получается нормально проверить нововведения, т.к. не могу стабильное соединение сделать себе.

Пока не стал собирать, просто запушил код сюда. Если есть возможность, то проверь код и отпишись по результатам.

Issue не закрываю пока, т.к. не понятно, пофиксилось или нет.

**Comment by sandlotie** [comment]
@YaNesyTortiK да, всё работает, спасибо

**Comment by YaNesyTortiK** [comment]
Версия 1.9.4 собрана и выпущена на pypi и в релизы.

**Comment by sandlotie** [comment]
@YaNesyTortiK мне кажется этот неявный `None` может быть проблемой
https://github.com/YaNesyTortiK/AnimeParsers/blob/2ad03273862282dade480bacb5b591a45449e2e8/src/anime_parsers_ru/parser_aniboom.py#L370
Тут неожиданный `requests.exceptions.MissingSchema` если всё таки вернётся `None`
https://github.com/YaNesyTortiK/AnimeParsers/blob/2ad03273862282dade480bacb5b591a45449e2e8/src/anime_parsers_ru/parser_aniboom.py#L478-L479 https://github.com/YaNesyTortiK/AnimeParsers/blob/2ad03273862282dade480bacb5b591a45449e2e8/src/anime_parsers_ru/parser_aniboom.py#L408 https://github.com/YaNesyTortiK/AnimeParsers/blob/2ad03273862282dade480bacb5b591a45449e2e8/src/anime_parsers_ru/parser_aniboom.py#L393

**Comment by YaNesyTortiK** [comment]
Ну да, может. В комментариях к функции я конечно написал, но думаю лучше тогда заменю на errors.NoResults

**Comment by YaNesyTortiK** [comment]
@sandlotie Заменил. Билд 1.9.5
